"""Registry de acciones del LCD — toggle/one-shot/info."""

ACTIONS = {
    # === TOOLS ===
    "lldp": {
        "title": "LLDP/CDP",
        "type": "oneshot",
        "method": "GET",
        "url": "/api/wired/lldp/parsed",
        "params": {},
        "description": "Discover neighbors",
        "feedback_text": "Scanning LLDP...",
        "feedback_seconds": 8,
        "result_fields": [
            ("Neighbor", "Neighbor", "{}"),
            ("Platform", "Platform", "{}"),
            ("Port",     "Remote port", "{}"),
            ("Mgmt IP",  "Mgmt IP", "{}"),
        ],
        "result_source": "rows",
    },
    "dhcp_stress": {
        "title": "DHCP Test",
        "type": "oneshot",
        "method": "GET",
        "url": "/api/network/dhcp",
        "params": {"requests": 50},
        "description": "Stress test DHCP",
        "feedback_text": "Stressing DHCP...",
        "feedback_seconds": 15,
        "warn_destructive": True,
        "result_fields": [],
    },
    "dns_bench": {
        "title": "DNS",
        "type": "oneshot",
        "method": "GET",
        "url": "/api/qc/dns",
        "params": {},
        "description": "DNS resolver test",
        "feedback_text": "Testing DNS...",
        "feedback_seconds": 5,
        "result_fields": [
            ("Domain", "domain", "{}"),
            ("Server", "server", "{}"),
            ("Result", "result", "{}"),
            ("Time",   "ms",     "{:.0f} ms"),
            ("Status", "ok",     "{}"),
        ],
    },
    "iperf_server": {
        "title": "iPerf Server",
        "type": "toggle",
        "start": {"method": "GET", "url": "/api/iperf/server/start"},
        "stop":  {"method": "GET", "url": "/api/iperf/server/stop"},
        "status": None,
        "status_field": None,
        "description": "TCP server :5201",
        "display_fields": [],
    },
    "iperf_client": {
        "title": "iPerf Client",
        "type": "oneshot",
        "method": "GET",
        "url": "/api/iperf/client",
        "params_dynamic": "iperf_client_params",
        "description": "Test to gateway",
        "feedback_text": "Testing...",
        "feedback_seconds": 12,
        "result_fields": [
            ("Server",  "server",      "{}"),
            ("TX",      "sent_mbps",   "{:.1f} Mbps"),
            ("RX",      "recv_mbps",   "{:.1f} Mbps"),
            ("Retrans", "retransmits", "{}"),
        ],
        "cache_result": True,
    },
    "hotspot": {
        "title": "Hotspot AP",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/hotspot/enable"},
        "stop":  {"method": "POST", "url": "/api/hotspot/disable"},
        "status": {"method": "GET", "url": "/api/hotspot/status"},
        "status_field": "enabled",
        "description": "NekoPi-Field SSID",
        "display_fields": [
            ("SSID",    "ssid",        "{}"),
            ("IP",      "ip",          "{}"),
            ("Clients", "clients",     "len"),
            ("Survey",  "survey_mode", "{}"),
        ],
        "refresh_seconds": 5,
    },
    "nat": {
        "title": "NAT Toggle",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/nat/enable"},
        "stop":  {"method": "POST", "url": "/api/nat/disable"},
        "status": {"method": "GET", "url": "/api/nat/status"},
        "status_field": "enabled",
        "description": "Forward eth0->eth1",
        "display_fields": [
            ("IP Fwd", "ip_forward", "{}"),
            ("Masq",   "masquerade", "{}"),
        ],
        "refresh_seconds": 5,
    },
    "captive_test": {
        "title": "Captive Test",
        "type": "oneshot",
        "method": "POST",
        "url": "/api/toolkit/captive/test",
        "params": {},
        "description": "Run captive detect",
        "feedback_text": "Testing...",
        "feedback_seconds": 5,
        "result_fields": [],
    },
    "network_traffic": {
        "title": "Net Traffic",
        "type": "info",
        "status": {"method": "GET", "url": "/api/network/traffic"},
        "status_field": None,
        "description": "Live RX/TX per interface",
        "refresh_seconds": 2,
    },

    # === CAPTURES ===
    "profiler": {
        "title": "Profiler",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/profiler/start"},
        "stop":  {"method": "POST", "url": "/api/profiler/stop"},
        "status": {"method": "GET", "url": "/api/profiler/status"},
        "status_field": "running",
        "description": "Client Profiler",
        "display_fields": [],
        "refresh_seconds": 5,
    },
    "kismet": {
        "title": "Kismet IDS",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/kismet/start"},
        "stop":  {"method": "POST", "url": "/api/kismet/stop"},
        "status": {"method": "GET", "url": "/api/kismet/status"},
        "status_field": "running",
        "description": "Dual-source IDS",
        "display_fields": [
            ("Interface", "iface", "{}"),
        ],
        "refresh_seconds": 5,
    },
    "ota_smart": {
        "title": "OTA Smart",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/ota/start"},
        "stop":  {"method": "POST", "url": "/api/ota/stop"},
        "status": {"method": "GET", "url": "/api/ota/status"},
        "status_field": "running",
        "description": "Smart channel capture",
        "display_fields": [
            ("Frames",  "frames",        "{}"),
            ("Elapsed", "elapsed",       "{:.0f}s"),
            ("Channel", "channel",       "{}"),
            ("Band",    "band",          "{}"),
            ("Mode",    "mode",          "{}"),
            ("Width",   "channel_width", "{}"),
        ],
        "refresh_seconds": 3,
    },
    "roaming": {
        "title": "Roaming",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/roaming/start"},
        "stop":  {"method": "POST", "url": "/api/roaming/stop"},
        "status": {"method": "GET", "url": "/api/roaming/status"},
        "status_field": "running",
        "description": "Roaming Analyzer",
        "display_fields": [
            ("Events",  "events",        "{}"),
            ("Roams",   "stats.roams",   "{}"),
            ("Deauths", "stats.deauths", "{}"),
            ("Avg FT",  "stats.avg_ft",  "{:.0f} ms"),
            ("SSID",    "target_ssid",   "{}"),
            ("Iface",   "iface",         "{}"),
        ],
        "refresh_seconds": 3,
    },

    # === SERVICES ===
    "sensor": {
        "title": "Sensor",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/sensor/services/start"},
        "stop":  {"method": "POST", "url": "/api/sensor/services/stop"},
        "status": {"method": "GET", "url": "/api/sensor/services/status"},
        "status_field": "ready",
        "description": "Influx + Grafana",
        "display_fields": [
            ("InfluxDB", "influxdb.running", "{}"),
            ("Grafana",  "grafana.running",  "{}"),
        ],
        "refresh_seconds": 5,
    },
    "radius": {
        "title": "RADIUS",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/radius/start"},
        "stop":  {"method": "POST", "url": "/api/radius/stop"},
        "status": {"method": "GET", "url": "/api/radius/status"},
        "status_field": "running",
        "description": "FreeRADIUS :1812",
        "display_fields": [
            ("IP",      "ip",      "{}"),
            ("Port",    "port",    "{}"),
            ("Uptime",  "uptime",  "{}"),
            ("Users",   "users",   "len"),
            ("Clients", "clients", "len"),
        ],
        "refresh_seconds": 5,
    },
    "mon0": {
        "title": "Mon0 Iface",
        "type": "toggle",
        "start": {"method": "POST", "url": "/api/monitor/setup"},
        "stop":  {"method": "POST", "url": "/api/monitor/teardown"},
        "status": {"method": "GET", "url": "/api/monitor/status"},
        "status_field": "mon0",
        "description": "AX210 monitor mode",
        "display_fields": [
            ("Channel", "mon0_channel", "{}"),
            ("Bands",   "mon0_bands",   "{}"),
            ("Scan IF", "scan_iface",   "{}"),
        ],
        "refresh_seconds": 5,
    },
    "ai_status": {
        "title": "Edge AI",
        "type": "info",
        "status": {"method": "GET", "url": "/api/ai/status"},
        "status_field": "online",
        "description": "AI provider status",
        "display_fields": [
            ("Backend", "backend",       "{}"),
            ("Model",   "model",         "{}"),
            ("Gemini",  "gemini.online", "{}"),
            ("Ollama",  "ollama.online", "{}"),
        ],
        "refresh_seconds": 10,
    },
}

SUBMENUS = {
    "tools":    ["lldp", "dhcp_stress", "dns_bench", "iperf_server",
                 "hotspot", "nat", "captive_test", "network_traffic"],
    "captures": ["profiler", "kismet", "ota_smart", "roaming"],
    "services": ["sensor", "radius", "mon0", "ai_status"],
}

HOME_STATUS_ICONS = ["profiler", "kismet", "ota_smart", "roaming"]
HOME_ICON_LABELS = {
    "profiler":  "PRF",
    "kismet":    "KSM",
    "ota_smart": "OTA",
    "roaming":   "ROAM",
}
